name: Auto Comment

on:
  issues:
    types: [opened]  # 触发条件：当问题被创建时
  pull_request:
    types: [opened]  # 触发条件：当拉取请求被创建时

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: actions/github-script@v4
        with:
          script: |
            if (context.payload.action === 'opened') {
              const issueComment = context.payload.issue ? issueOpened : pullRequestOpened;
              await github.issues.createComment({
                ...context.repo,
                issue_number: context.payload.issue.number,
                body: issueComment
              });
            }