name: Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入内容（如发布资产）
      actions: read    # 允许读取 GitHub Actions 的详细信息
      deployments: write  # 允许写入部署信息
      issues: write     # 允许写入问题
      pull-requests: write  # 允许写入拉取请求
      security-events: write  # 允许写入安全事件
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --strip 'footer' --exclude-path '.github/**'
        env:
          OUTPUT: CHANGELOG.md

      - name: Get release information
        id: release_info
        run: |
          echo "RELEASE_ID=$(echo ${{ github.event.release.id }})" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(echo ${{ github.event.release.tag_name }})" >> $GITHUB_ENV

      - name: Update release description
        run: |
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID \
            -d "{\"body\": \"$CHANGELOG_CONTENT\"}"
