name: Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入内容（如发布资产）
      actions: read    # 允许读取 GitHub Actions 的详细信息
      deployments: write  # 允许写入部署信息
      issues: write     # 允许写入问题
      pull-requests: write  # 允许写入拉取请求
      security-events: write  # 允许写入安全事件

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --strip 'footer' --exclude-path '.github/**'
        env:
          OUTPUT: CHANGELOG.md

      - name: Get release information
        id: release_info
        run: |
          echo "RELEASE_ID=$(echo ${{ github.event.release.id }})" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(echo ${{ github.event.release.tag_name }})" >> $GITHUB_ENV

      - name: Create a release
        id: create_release
        run: |
          CHANGELOG_CONTENT=$(cat CHANGELOG.md | jq -R .)  # 使用 jq 转义内容
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"${{ github.event.release.tag_name }}\",\"target_commitish\":\"master\",\"name\":\"${{ github.event.release.tag_name }}\",\"body\":$CHANGELOG_CONTENT,\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false}")

          echo "Response: $response"
          echo "$response" | jq '.id'  # 输出发布的 ID

      - name: Update release description
        run: |
          CHANGELOG_CONTENT=$(cat CHANGELOG.md | jq -R .)  # 使用 jq 转义内容
          response=$(curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID \
            -d "{\"body\": $CHANGELOG_CONTENT}")

          echo "Response: $response"
          echo "$response" | jq '.body'  # 输出更新后的发布描述
