name: Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --strip 'footer' --exclude-path '.github/**'
        env:
          OUTPUT: CHANGELOG.md

      - name: List files
        run: ls -la  # 列出当前目录的文件

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"