# cliff.toml
[header]
title = "Changelog"
date_format = "%Y-%m-%d"

[sections]
[[sections.features]]
title = "Features"
prefix = "feat:"

[[sections.bugfixes]]
title = "Bug Fixes"
prefix = "fix:"

[[sections.others]]
title = "Other Changes"